Finished bubble sort and bubble sort by functions
edlingao/bubble-sort pull request #1
Opened 2019-04-25 17:33 UTC by edlingao

2019-04-25 19:25 UTC, inhaq requested changes
Good job on the first ruby project. Kindly add linter to your project and refactor code by the following comment. 
Once updated kindly resubmit for review.

2019-04-25 19:25 UTC, inhaq commented on BubbleSortBy.rb
> +            if(!yield_true ||left_or_right < 1 )
you can check block with `block_given?` kindly refactor accordingly

2019-04-25 21:39 UTC, edlingao commented
Commited every change, succefully refactor

2019-04-26 05:21 UTC, inhaq approved these changes
It's 👍🏻go ahead and submit your project. 
Good luck with the next project.

2019-04-29 04:42 UTC, merged